version: "3.7"

services:
  pg:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: todo_app
      POSTGRES_PASSWORD: secret_maks
      POSTGRES_DB: todos

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@todo.com"
      PGADMIN_DEFAULT_PASSWORD: "secret_maks"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 54320:80

  app:
    image: node:12-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      PGHOST: pg
      PGUSER: todo_app
      PGPASSWORD: secret_maks
      PGDATABASE: todos

volumes:
  postgres_data:
  pgadmin:
